name: Unit Tests

on: 
  push:
    branches:
      - '**'
    pull_request:
      branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2


  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Linting
        run: |
          pnpm i 
          pnpm i turbo -g
          turbo cd:lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          pnpm i 
          pnpm add turbo -g
          turbo cd:test