name: Unit Tests

on: 
  push:
    branches:
      - '**'
    pull_request:
      branches: [main]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Linting
        run: |
          pnpm i 
          pnpm i turbo -g
          turbo cd:lint
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          npm i pnpm -g
          pnpm i 
          pnpm add turbo -g
          turbo cd:test